#latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
orbs:
  node: circleci/node@5
  heroku: circleci/heroku@1.2.6
commands:
  env-setup:
    name: Project setup and dependencies installation
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  run-tests:
    executor: node/default
    parallelism: 2
    steps:
      - env-setup
      - run:
          name: Run Tests
          command: npm test
  build-app:
    executor: node/default
    steps:
      - env-setup
      - run:
          name: Project is Building
          command: npm run build
      - persist_to_workspace: 
          root: ~/project
          paths:
            - .
  deploy-build:
    executor: node/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true  
workflows:
  build-and-deploy:
    jobs:
      - run-tests
      - build-app
      - hold-for-approval:
          type: approval
          requires:
            - run-tests
            - build-app
      - deploy-build:
          requires:
            - hold-for-approval
          filters:
            branches:
              only: main #deploy only for the main branch.